import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox', '--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 853 } });
await page.goto('https://frontend-production-ba31.up.railway.app/map', { waitUntil: 'networkidle', timeout: 60_000 });
await page.getByText(/Most at risk now/i).waitFor({ state: 'visible', timeout: 30_000 });
await page.waitForTimeout(2200);
await page.locator('.leaflet-pm-icon-polygon').first().click();
const box = await page.locator('[aria-label*="early warning map"]').boundingBox();
if (!box) throw new Error('map bounds unavailable');
const points = [[box.x + 780, box.y + 350], [box.x + 850, box.y + 350], [box.x + 850, box.y + 430], [box.x + 780, box.y + 430], [box.x + 780, box.y + 350]];
for (const [x, y] of points) await page.mouse.click(x, y);
await page.waitForTimeout(900);
await page.mouse.click(points[0][0], points[0][1]);
await page.getByLabel('Area of interest').waitFor({ state: 'visible', timeout: 30_000 });
await page.getByText(/Community reports/).waitFor({ state: 'visible', timeout: 30_000 });
const panel = page.getByLabel('Area of interest');
const scrollable = panel.locator('.overflow-y-auto');
await scrollable.evaluate((el) => { el.scrollTop = el.scrollHeight; });
await page.waitForTimeout(400);
await page.screenshot({ path: '/home/muga/hali/screenshots/06-aoi-polygon-query.png' });
await browser.close();
