#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/clips"
FFMPEG="${FFMPEG:-$(cd ../.. && pwd)/node_modules/ffmpeg-static/ffmpeg}"
command -v "$FFMPEG" >/dev/null 2>&1 || { echo "ffmpeg executable not found: $FFMPEG" >&2; exit 1; }
declare -A CAPTIONS=(
  [01]="No account. No login. Real alerts, live from the pipeline."
  [02]="One alert, ten languages, generated by AI, not looked up from a table."
  [03]="ICPAC's own hazard layers, plus district-level risk, not just eight country outlines."
  [04]="Draw any area. Get live alerts, reports, and population inside it."
  [05]="Every translation is scored across three AI models. The clearest one wins."
  [06]="Same alert, three livelihoods, three genuinely different action plans."
  [07]="A community report just created a hotspot with no official alert yet."
)
for n in 01 02 03 04 05 06 07; do
  [ -f "beat-$n.webm" ] || { echo "missing beat-$n.webm" >&2; exit 1; }
  "$FFMPEG" -y -i "beat-$n.webm" -vf "subtitles=../captions/$n.ass" -c:v libx264 -preset fast -crf 20 -c:a aac "captioned-$n.mp4" >/dev/null 2>&1
done
for n in 01 02 03 04 05 06 07; do echo "file 'captioned-$n.mp4'"; done > concat_list.txt
"$FFMPEG" -y -f concat -safe 0 -i concat_list.txt -c copy web-segments-rough-cut.mp4 >/dev/null 2>&1
echo "captioned clips and rough cut written to $(pwd)"
